import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
[env]
TERM = "xterm-256color"
[scrolling]
history = 100000
[font.normal]
family = "Fira Code Nerd Font"
[font]
size = 8.0
[keyboard]
bindings = [{key="NumpadEnter", chars="\r"}]
